services:
    proxybonanza.plan.repository:
        class: WowApps\ProxyBonanzaBundle\Repository\PlanRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ['WowApps\ProxyBonanzaBundle\Entity\Plan']
    proxybonanza.proxies.repository:
        class: WowApps\ProxyBonanzaBundle\Repository\ProxiesRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ['WowApps\ProxyBonanzaBundle\Entity\Proxy']
    proxybonanza.authips.repository:
        class: WowApps\ProxyBonanzaBundle\Repository\AuthIpsRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ['WowApps\ProxyBonanzaBundle\Entity\AuthIps']
