services:
    proxybonanza.plan.repository:
        public: false
        class: WowApps\ProxybonanzaBundle\Repository\PlanRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['WowApps\ProxybonanzaBundle\Entity\Plan']
    proxybonanza.proxies.repository:
        public: false
        class: WowApps\ProxybonanzaBundle\Repository\ProxiesRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['WowApps\ProxybonanzaBundle\Entity\Proxy']
    proxybonanza.authips.repository:
        public: false
        class: WowApps\ProxybonanzaBundle\Repository\AuthIpsRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['WowApps\ProxybonanzaBundle\Entity\AuthIps']
