services:
    wowapps.proxybonanza:
        alias: WowApps\ProxybonanzaBundle\Service\ProxyBonanza
        public: true
    WowApps\ProxybonanzaBundle\Service\ProxyBonanza:
        public: false
        arguments:
            - '%wowapps.proxybonanza.config%'
            - '@proxybonanza.plan.repository'
            - '@proxybonanza.proxies.repository'
            - '@proxybonanza.authips.repository'
