services:
    wowapps.proxybonanza:
        class: WowApps\ProxyBonanzaBundle\Service\ProxyBonanza
        arguments:
            - %wowapps.proxybonanza.config%
            - "@proxybonanza.plan.repository"
            - "@proxybonanza.proxies.repository"
            - "@proxybonanza.authips.repository"
